apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: bind
  name: bind
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bind
    spec:
      containers:
      - image: sameersbn/bind:9.11.3-20190706
        name: bind
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
        - containerPort: 10000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: bind-claim0
      restartPolicy: Always
      volumes:
      - name: bind-claim0
        persistentVolumeClaim:
          claimName: bind-claim0
status: {}
