kind: ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: letsencrypt-staging
  annotations:
    certmanager.k8s.io/acme-challenge-type: 'http01'
    certmanager.k8s.io/issuer: 'letsencrypt-staging'
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: marc.heimann@swisslog.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
  tls:
  - secretName: swisslog-cicd-tls-staging
    hosts:
    - example.com
    - api.example.com
    - www.example.com
