apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2019-05-13T14:37:04Z","generation":1,"labels":{"app":"minio","chart":"minio-1.6.3","heritage":"Tiller","release":"spinnaker"},"name":"spinnaker-minio","namespace":"default","resourceVersion":"21131406","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/spinnaker-minio","uid":"93e4a39b-758c-11e9-a929-00505699e9e3"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"minio","release":"spinnaker"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"minio","release":"spinnaker"},"name":"spinnaker-minio"},"spec":{"containers":[{"command":["/bin/sh","-ce","cp /tmp/config.json /root/.minio/ \u0026\u0026 /usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server /export"],"env":[{"name":"MINIO_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"accesskey","name":"spinnaker-minio"}}},{"name":"MINIO_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"secretkey","name":"spinnaker-minio"}}}],"image":"minio/minio:RELEASE.2018-08-25T01-56-38Z","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":9000},"timeoutSeconds":1},"name":"minio","ports":[{"containerPort":9000,"name":"service","protocol":"TCP"}],"resources":{"requests":{"cpu":"250m","memory":"256Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/export","name":"export"},{"mountPath":"/tmp/config.json","name":"minio-server-config","subPath":"config.json"},{"mountPath":"/root/.minio/","name":"minio-config-dir"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"export","persistentVolumeClaim":{"claimName":"spinnaker-minio"}},{"configMap":{"defaultMode":420,"name":"spinnaker-minio"},"name":"minio-server-config"},{"name":"minio-user","secret":{"defaultMode":420,"secretName":"spinnaker-minio"}},{"emptyDir":{},"name":"minio-config-dir"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2019-05-13T14:37:04Z","lastUpdateTime":"2019-05-13T14:37:07Z","message":"ReplicaSet \"spinnaker-minio-67598bf9cd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-08-03T11:32:51Z","lastUpdateTime":"2019-08-03T11:32:51Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2019-08-19T10:27:37Z"
  generation: 3
  labels:
    app: minio
    chart: minio-1.6.3
    heritage: Tiller
    release: spinnaker
  name: spinnaker-minio
  namespace: default
  resourceVersion: "31186621"
  selfLink: /apis/apps/v1/namespaces/default/deployments/spinnaker-minio
  uid: 957252ea-5350-40a3-8f68-b4cba143d7ab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      release: spinnaker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        release: spinnaker
      name: spinnaker-minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - cp /tmp/config.json /root/.minio/ && /usr/bin/docker-entrypoint.sh minio
          -C /root/.minio/ server /export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: spinnaker-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: spinnaker-minio
        image: minio/minio:RELEASE.2018-08-25T01-56-38Z
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        name: minio
        ports:
        - containerPort: 9000
          name: service
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: export
        - mountPath: /tmp/config.json
          name: minio-server-config
          subPath: config.json
        - mountPath: /root/.minio/
          name: minio-config-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: export
        persistentVolumeClaim:
          claimName: spinnaker-minio
      - configMap:
          defaultMode: 420
          name: spinnaker-minio
        name: minio-server-config
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: spinnaker-minio
      - emptyDir: {}
        name: minio-config-dir
